"""Power-transformer fault-diagnosis ontology (TBox) and knowledge-graph builder.

The ontology is the single source of truth for the schema used throughout the
pipeline. It is built programmatically with :mod:`rdflib` so that it is always
internally consistent (every property used by the reasoner is declared) and so
that the serialized ``.ttl`` / ``.owl`` files are reproducible build artifacts.

Design notes
------------
* The schema separates **assets**, **measurements**, **symptoms**, **faults**,
  **causes**, **effects** and **maintenance actions** so that an inferred
  diagnosis can be traced from sensor evidence to a recommended action.
* The fault taxonomy mirrors the **IEC 60599** dissolved-gas fault codes.
* Provenance is expressed with the **W3C PROV-O** vocabulary: every inferred
  diagnosis is a ``prov:Entity`` generated by a rule-application ``prov:Activity``
  that ``prov:used`` the supporting measurements.
* Every class and property carries an ``rdfs:label`` and ``rdfs:comment``.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from pathlib import Path

import pandas as pd
from rdflib import Graph, Literal, Namespace, URIRef
from rdflib.namespace import OWL, PROV, RDF, RDFS, XSD

from .rules import FAULT_LABELS, GAS_COLUMN_ALIASES

# Base namespace (kept stable for backward compatibility with the publication).
ONTO = Namespace("http://test.org/onto-pw#")
BASE_IRI = "http://test.org/onto-pw"

# Default measurement units by friendly column name.
PARAMETER_UNITS: dict[str, str] = {
    "Hydrogen": "uL/L",
    "Oxygen": "uL/L",
    "Nitrogen": "uL/L",
    "Methane": "uL/L",
    "CO": "uL/L",
    "CO2": "uL/L",
    "Ethylene": "uL/L",
    "Ethane": "uL/L",
    "Acetylene": "uL/L",
    "DBDS": "mg/kg",
    "Power factor": "%",
    "Interfacial V": "mN/m",
    "Dielectric rigidity": "kV",
    "Water content": "mg/kg",
    "Health index": "%",
    "Life expectation": "years",
}


def _local(name: str) -> URIRef:
    return ONTO[name]


def _add_class(
    g: Graph, name: str, label: str, comment: str, parent: URIRef | None = None
) -> URIRef:
    cls = _local(name)
    g.add((cls, RDF.type, OWL.Class))
    g.add((cls, RDFS.label, Literal(label)))
    g.add((cls, RDFS.comment, Literal(comment)))
    if parent is not None:
        g.add((cls, RDFS.subClassOf, parent))
    return cls


def _add_object_property(
    g: Graph, name: str, label: str, comment: str, domain: URIRef, rang: URIRef
) -> URIRef:
    prop = _local(name)
    g.add((prop, RDF.type, OWL.ObjectProperty))
    g.add((prop, RDFS.label, Literal(label)))
    g.add((prop, RDFS.comment, Literal(comment)))
    g.add((prop, RDFS.domain, domain))
    g.add((prop, RDFS.range, rang))
    return prop


def _add_data_property(
    g: Graph, name: str, label: str, comment: str, domain: URIRef, rang: URIRef
) -> URIRef:
    prop = _local(name)
    g.add((prop, RDF.type, OWL.DatatypeProperty))
    g.add((prop, RDFS.label, Literal(label)))
    g.add((prop, RDFS.comment, Literal(comment)))
    g.add((prop, RDFS.domain, domain))
    g.add((prop, RDFS.range, rang))
    return prop


def build_tbox() -> Graph:
    """Return a fresh graph containing the full ontology schema (TBox)."""
    g = Graph()
    g.bind("", ONTO)
    g.bind("owl", OWL)
    g.bind("rdfs", RDFS)
    g.bind("prov", PROV)
    g.bind("xsd", XSD)

    onto_uri = URIRef(BASE_IRI)
    g.add((onto_uri, RDF.type, OWL.Ontology))
    g.add((onto_uri, RDFS.label, Literal("Power Transformer Root Cause Analysis Ontology")))
    g.add(
        (
            onto_uri,
            RDFS.comment,
            Literal(
                "Modular ontology for explainable, knowledge-graph-based root "
                "cause analysis of power transformers. Fault taxonomy follows "
                "IEC 60599; provenance follows W3C PROV-O."
            ),
        )
    )

    # --- core entities ----------------------------------------------------
    asset = _add_class(g, "Asset", "Asset", "A physical industrial asset under diagnosis.")
    transformer = _add_class(
        g,
        "Transformer",
        "Transformer",
        "A high-voltage power transformer (specialisation of Asset).",
        asset,
    )
    component = _add_class(
        g, "Component", "Component", "A constituent component of an asset.", asset
    )
    _add_class(g, "Sensor", "Sensor", "A device that produces measurements of an asset.")
    measurement = _add_class(
        g,
        "Measurement",
        "Measurement",
        "An observed quantitative value for a monitored parameter.",
    )
    _add_class(
        g,
        "DGAMeasurement",
        "DGA measurement",
        "A dissolved-gas-analysis measurement (gas concentration in oil).",
        measurement,
    )
    _add_class(
        g,
        "OilQualityMeasurement",
        "Oil-quality measurement",
        "An insulating-oil quality measurement (e.g. moisture, breakdown voltage).",
        measurement,
    )
    measured_property = _add_class(
        g,
        "MeasuredProperty",
        "Measured property",
        "A monitored physical/chemical property that a measurement observes.",
    )

    symptom = _add_class(
        g,
        "Symptom",
        "Symptom",
        "An observable abnormal condition derived from measurements.",
    )
    fault = _add_class(
        g,
        "Fault",
        "Fault",
        "An incipient or active fault condition affecting an asset.",
    )
    cause = _add_class(g, "Cause", "Cause", "A root cause that explains one or more faults.")
    effect = _add_class(g, "Effect", "Effect", "A consequence or effect produced by a fault.")
    action = _add_class(
        g,
        "MaintenanceAction",
        "Maintenance action",
        "A recommended maintenance or inspection action.",
    )
    _add_class(
        g,
        "OperatingCondition",
        "Operating condition",
        "Context describing how the asset is being operated (e.g. loading).",
    )
    diagnosis = _add_class(
        g,
        "Diagnosis",
        "Diagnosis",
        "An inferred diagnostic conclusion for an asset, with explanation trace.",
    )
    evidence = _add_class(
        g,
        "Evidence",
        "Evidence",
        "An auditable piece of evidence (parameter, value, threshold) for a rule.",
    )
    rule = _add_class(
        g,
        "DiagnosticRule",
        "Diagnostic rule",
        "A documented rule whose application produces diagnoses.",
    )

    # --- fault taxonomy (IEC 60599) --------------------------------------
    fault_class_names = {
        "PD": "PartialDischarge",
        "D1": "LowEnergyDischarge",
        "D2": "HighEnergyDischarge",
        "T1": "ThermalFaultLow",
        "T2": "ThermalFaultMedium",
        "T3": "ThermalFaultHigh",
    }
    for code, cname in fault_class_names.items():
        cls = _add_class(g, cname, FAULT_LABELS[code], FAULT_LABELS[code], fault)
        g.add((cls, ONTO.faultCode, Literal(code)))

    # --- legacy measured properties (kept for continuity) ----------------
    for name, label in (
        ("Water_content", "Water content"),
        ("Health_index", "Health index"),
        ("Life_expectation", "Life expectation"),
        ("DBDS", "DBDS"),
        ("Power_factor", "Power factor"),
        ("Interfacial_V", "Interfacial tension"),
        ("Dielectric_rigidity", "Dielectric rigidity"),
    ):
        _add_class(
            g,
            name,
            label,
            f"Measured property: {label}.",
            measured_property,
        )

    # --- gases ------------------------------------------------------------
    gas = _add_class(
        g, "Gas", "Gas", "A fault gas dissolved in transformer oil.", measured_property
    )
    for gname in (
        "Hydrogen",
        "Oxygen",
        "Nitrogen",
        "Methane",
        "CO",
        "CO2",
        "Ethylene",
        "Ethane",
        "Acetylene",
    ):
        _add_class(g, gname, gname, f"Dissolved fault gas: {gname}.", gas)

    # --- object properties ------------------------------------------------
    _add_object_property(
        g,
        "hasComponent",
        "has component",
        "Links an asset to its components.",
        asset,
        component,
    )
    _add_object_property(
        g,
        "hasMeasurement",
        "has measurement",
        "Links an asset to a measurement observed on it.",
        asset,
        measurement,
    )
    _add_object_property(
        g,
        "observedProperty",
        "observed property",
        "The measured property that a measurement observes.",
        measurement,
        measured_property,
    )
    _add_object_property(
        g,
        "hasSymptom",
        "has symptom",
        "Links an asset to an observed symptom.",
        asset,
        symptom,
    )
    _add_object_property(
        g,
        "hasDiagnosis",
        "has diagnosis",
        "Links an asset to an inferred diagnosis.",
        asset,
        diagnosis,
    )
    _add_object_property(
        g,
        "ofAsset",
        "of asset",
        "The asset a diagnosis refers to.",
        diagnosis,
        asset,
    )
    _add_object_property(
        g,
        "indicatesFault",
        "indicates fault",
        "Links a diagnosis to the fault it identifies.",
        diagnosis,
        fault,
    )
    _add_object_property(
        g,
        "hasRootCause",
        "has root cause",
        "Links a diagnosis or fault to its root cause.",
        diagnosis,
        cause,
    )
    _add_object_property(
        g,
        "hasEffect",
        "has effect",
        "Links a fault to one of its effects.",
        fault,
        effect,
    )
    _add_object_property(
        g,
        "recommendsAction",
        "recommends action",
        "Links a diagnosis to a recommended maintenance action.",
        diagnosis,
        action,
    )
    _add_object_property(
        g,
        "supportedByEvidence",
        "supported by evidence",
        "Links a diagnosis to a supporting piece of evidence.",
        diagnosis,
        evidence,
    )
    _add_object_property(
        g,
        "derivedFromRule",
        "derived from rule",
        "Links a diagnosis to the diagnostic rule that produced it.",
        diagnosis,
        rule,
    )
    # Backward-compatible water-content relations (now both declared).
    _add_object_property(
        g,
        "relatesToWaterContent",
        "relates to water content",
        "Links a transformer to its water-content measurement.",
        transformer,
        _local("Water_content"),
    )
    _add_object_property(
        g,
        "relatesWaterContentToMeasurement",
        "relates water content to measurement",
        "Links a water-content property to its measurement.",
        _local("Water_content"),
        measurement,
    )

    # --- datatype properties ---------------------------------------------
    _add_data_property(
        g,
        "hasValue",
        "has value",
        "Numeric value of a measurement or evidence item.",
        measurement,
        XSD.double,
    )
    _add_data_property(
        g,
        "hasUnit",
        "has unit",
        "Unit of measure for a value.",
        measurement,
        XSD.string,
    )
    _add_data_property(
        g,
        "hasWaterLevel",
        "has water level",
        "Water content level of a measurement.",
        _local("Water_content"),
        XSD.double,
    )
    _add_data_property(
        g,
        "faultCode",
        "fault code",
        "IEC 60599 fault code (PD, D1, D2, T1, T2, T3).",
        fault,
        XSD.string,
    )
    _add_data_property(
        g,
        "hasStatus",
        "has status",
        "Overall diagnostic status of the asset.",
        diagnosis,
        XSD.string,
    )
    _add_data_property(
        g,
        "hasSeverity",
        "has severity",
        "Severity ranking of a fault/diagnosis.",
        diagnosis,
        XSD.string,
    )
    _add_data_property(
        g,
        "hasExplanation",
        "has explanation",
        "Human-readable explanation trace for a diagnosis.",
        diagnosis,
        XSD.string,
    )
    return g


# ---------------------------------------------------------------------------
# ABox materialisation
# ---------------------------------------------------------------------------


def _asset_uri(asset_id: str) -> URIRef:
    return ONTO[str(asset_id).replace(" ", "_")]


def materialize_assets(g: Graph, measurements: pd.DataFrame, asset_column: str = "Asset") -> Graph:
    """Add asset and measurement individuals from a measurements table."""
    df = measurements.copy()
    if asset_column not in df.columns:
        df[asset_column] = [f"PW{101 + i}" for i in range(len(df))]

    for _, row in df.iterrows():
        asset_id = str(row[asset_column])
        asset = _asset_uri(asset_id)
        g.add((asset, RDF.type, ONTO.Transformer))
        g.add((asset, RDFS.label, Literal(asset_id)))
        for column, value in row.items():
            if column == asset_column or pd.isna(value):
                continue
            prop_name = str(column).replace(" ", "_")
            meas = ONTO[f"{asset_id}_{prop_name}"]
            is_gas = column in GAS_COLUMN_ALIASES and column not in {"CO", "CO2", "O2"}
            meas_class = (
                ONTO.DGAMeasurement
                if column in GAS_COLUMN_ALIASES
                else (ONTO.OilQualityMeasurement)
            )
            g.add((meas, RDF.type, meas_class))
            g.add((asset, ONTO.hasMeasurement, meas))
            g.add((meas, ONTO.observedProperty, ONTO[prop_name]))
            g.add((meas, ONTO.hasValue, Literal(float(value), datatype=XSD.double)))
            unit = PARAMETER_UNITS.get(str(column))
            if unit:
                g.add((meas, ONTO.hasUnit, Literal(unit)))
            # Backward-compatible water level triple.
            if column == "Water content":
                g.add((asset, ONTO.relatesToWaterContent, meas))
                g.add((meas, ONTO.hasWaterLevel, Literal(float(value), datatype=XSD.double)))
            _ = is_gas
    return g


def row_to_gas_dict(row: Mapping[str, float]) -> dict[str, float]:
    """Translate a friendly measurement row into gas-symbol keys (H2, CH4, ...)."""
    gases: dict[str, float] = {}
    for column, symbol in GAS_COLUMN_ALIASES.items():
        if column in row and not pd.isna(row[column]):
            gases[symbol] = float(row[column])
    return gases


def build_knowledge_graph(measurements: pd.DataFrame) -> Graph:
    """Build a knowledge graph: TBox schema + materialised asset measurements."""
    g = build_tbox()
    materialize_assets(g, measurements)
    return g


def serialize_ontology(output_dir: str | Path) -> dict[str, Path]:
    """Serialize the TBox to Turtle and RDF/XML; return the written paths."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    g = build_tbox()
    ttl = out / "onto_pw.ttl"
    owl = out / "onto_pw.owl"
    g.serialize(destination=ttl, format="turtle")
    g.serialize(destination=owl, format="pretty-xml")
    return {"ttl": ttl, "owl": owl}


def iter_class_descriptions(g: Graph | None = None) -> Iterable[tuple[str, str]]:
    """Yield ``(label, comment)`` for every described class (documentation aid)."""
    graph = g if g is not None else build_tbox()
    for cls in graph.subjects(RDF.type, OWL.Class):
        label = graph.value(cls, RDFS.label)
        comment = graph.value(cls, RDFS.comment)
        if label is not None and comment is not None:
            yield (str(label), str(comment))
